name: 'setup_cache'
description: 'sets up the shared cache'
inputs:
  compiler_key:
    required: true
    description: Compiler to key on

runs:
  using: "composite"
  steps:
    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.ccache
          ~/.conan
        key: v1-${{ runner.os }}-${{ inputs.compiler_key }}-${{ github.sha }}
        # actions/cache does not overwrite previous cache entries, so use the trick of restoring
        # most recent key by prefix, then saving changes under a new cache.
        restore-keys: v1-${{ runner.os }}-${{ inputs.compiler_key }}-

