name: 'setup_cache'
description: 'sets up the shared cache'
inputs:
  compiler:
    required: true
    type: string
  build_type:
    required: true
    type: string
  generator:
    required: true
    type: string
  developer_defaults:
    required: true
    type: string


runs:
  using: "composite"
  steps:
    - name: Cache
      uses: actions/cache@v3
      with:
        # You might want to add .ccache to your cache configuration?
        path: |
          ~/.cache/pip
          ~/.ccache
          ~/.conan
        key: ${{ runner.os }}-${{ inputs.compiler }}-${{ inputs.build_type }}-${{ inputs.generator }}-${{ inputs.developer_defaults }}-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.compiler }}-${{ inputs.build_type }}

