macro(cucumber_cpp_runner_enable_ipo)
	include(CheckIPOSupported)
	check_ipo_supported(RESULT result OUTPUT output)
	if (result)
		set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)
	else ()
		message(WARNING "IPO requested but not supported")
		message(DEBUG ${output})
	endif ()
endmacro()
